### ISSUE TITLE
Monteur `local-system` requires `Method` and `Archive` When Not Needed

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#1]
# Description
```
Please provide a short description of what you have encountered below.
```
Apparently, for Setup API, when the recipe is set to `local-system`, it was required to set `method` and `archive` in `source` when it is not needed. Both of them only being used when the recipe is `http` source.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
Setup API does not force user to fill in `method` and `archive` when `local-system` recipe type is used.

# Current Behavior
```
Please specify the current behavior of software below.
```
Setup API is forcing user to fill in `method` and `archive` when `local-system` recipe type is used.

Fortunately, you can workaround it by feeding some junk data as both of them appeared to be unused.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
1. Create a recipe with `local-system` without `method` and `archive`.
2. run `monteur setup`. Observe the error.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
