### ISSUE TITLE
Add Host Lock Checking Function

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#10]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
In some projects like building operating system, they requires specific host system to operate. Right now, there is NO WAY for Monteur to lock the host system requirements.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Monteur is capable to restrict its operations by host system requirement locking via `workspace.toml`.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Monteur operate blindly without any checking.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
