### ISSUE TITLE
Add Native DEB Package Function

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#12]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
The current `.deb` package function is relying on `debuild` 3rd-party software which only work on Debian-based operating system. Since we wants Montuer to work anywhere everywhere whenever possible, we have to offer this packaging function natively.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Monteur can package `.deb` natively that complies to Debian standards.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Monteur cannot package `.deb` natively.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```
1. https://github.com/guillemj/dpkg/tree/main/src/deb
2. https://wiki.debian.org/Teams/Dpkg
3. https://github.com/goreleaser/nfpm/blob/main/deb/deb.go
4. https://lintian.debian.org/tags/
5. https://tldp.org/HOWTO/Debian-Binary-Package-Building-HOWTO/x60.html
6. https://debian-handbook.info/browse/stable/sect.package-meta-information.html
7. https://en.wikipedia.org/wiki/Deb\_(file_format)

**Comment by hollowaykeanho** [comment]
Dependent on https://github.com/ZORALab/Monteur/issues/5

**Comment by hollowaykeanho** [comment]
Implemented native `tar` support.

**Comment by hollowaykeanho** [comment]
Dependent on https://github.com/ZORALab/Monteur/issues/13

**Comment by hollowaykeanho** [comment]
Need to explore the algorithmic approach by reverse engineering.

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
