### ISSUE TITLE
Allow CI-Job to Perform Multi-Phase Jobs

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#14]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
Current Monteur implementation of parallel executions are good but there is a need to perform multi-phase jobs, like compile the dependencies first before compiling the project. Right now, Monteur can't offer this function at the moment.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
Monteur is capable of offering multi-phase job executions on top of its current parallel executions.

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Monteur cannot operate multi-phase job executions.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
