### ISSUE TITLE
Add Report Job

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#15]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
Allows user to fully operate the CI locally here and only perform reporting to the 3rd-party service provider like test coverage and build status badges.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
There is a dedicated Report Job for performing the reporting.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Report Job is not available. Currently, only workaround would be embedded into existing recipe.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
