### ISSUE TITLE
Setup Job's https-download Type Failed To Handle raw Type

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#16]
# Description
```
Please provide a short description of what you have encountered below.
```
There is an issue where downloading a `raw` file via `https-download` in Setup Job failed for unknown reason. The downloader detects the raw file as directory and `Sources.[OS]-[ARCH].Archive` cannot be left blank.

Therefore it is concluded that the `https-download` failed to download a raw file.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
`https-download` can accept empty or absent `Sources.[OS]-[ARCH].Archive` field to handle raw file download.

# Current Behavior
```
Please specify the current behavior of software below.
```
`https-download` cannot accept empty or absent `Sources.[OS]-[ARCH].Archive` field to handle raw file download while no workaround is available.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
Set `https-download` to download a raw file. Observe the error messages.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by JeanShuralyov** [comment]
+1... This is important.

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
