### ISSUE TITLE
Rename SaveStderr to SaveSTDERR

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#4]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
Standardized Acronym naming convention in CEU. Since all acronyms used in the project are UPPERCASE, `SaveStderr` in CEU should not be an excuse. Let's correct it.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
`SaveSTDERR` is implemented and backward compatible with `SaveStderr`.

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
`SaveStderr` is not complying to the uppercase naming convention.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
