### ISSUE TITLE
Support Native ar Archive Function

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#5]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
To enable built-in `deb` packaging function, `ar` function is required since it is used to archive the `.deb` foundation. Therefore, we **MUST** support `ar` archive function natively before anything else.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Monteur can now offer native `ar` archive function.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Montuer must rely on external `ar` software to compress `ar` format.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by JeanShuralyov** [comment]
+1... This is important.

**Comment by corygalyna** [comment]
Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI
