### ISSUE TITLE
Add Chroot Interfacing Function to CEU

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Monteur#9]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
Since we want Monteur to be capable of building Debian operating system from scratch with secure boot and etc, we have to at least support `chroot` first to configure the target operating system in the Monteur's CEU.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Monteur CEU is capable of doing `chroot`.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Monteur CEU is not capable of doing `chroot`.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by corygalyna** [comment]
[Closing this project as it shall be replaced using https://github.com/ChewKeanHo/AutomataCI](url)
